site_name: Test site
site_description: Mkdocs tests site
site_author: Lukas Holota
site_url: https://www.example.com/

nav:
  - Index: index.md

# Configuration
theme:
  name: material
  language: en
  palette:
    primary: deep orange
    accent: deep orange
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - drawio-exporter:
      # Diagrams are cached to speed up site generation. The default path is
      # drawio-exporter, relative to the documentation directory.
      cache_dir: 'drawio-exporter'
      # Path to the Draw.io executable:
      #   * drawio on Linux
      #   * draw.io on macOS
      #   * or draw.io.exe on Windows
      # We'll look for it on your system's PATH, then default installation
      # paths. If we can't find it we'll warn you.
      drawio_executable: null
      # Additional Draw.io CLI args
      drawio_args:
        - --no-sandbox
      # Output format (see draw.io --help | grep format)
      format: svg
      # Glob pattern for matching source files
      sources: '*.drawio'